from hashlib import sha256

# Getting DB connection
import connection
mycon, myCursor = connection.getConnection()

# Checking if db exists
myCursor.execute("Show databases")

for db in myCursor:
    # if db exists, drop it
    if(db[0] == "kuchbhi"):
        myCursor.reset()
        myCursor.execute("DROP DATABASE kuchbhi")

# Create new database and use it
myCursor.execute("CREATE DATABASE kuchbhi")
myCursor.execute("use kuchbhi")

# --- Creating Tables ---

# Customers Table
myCursor.execute("CREATE TABLE customers(name VARCHAR(255), number VARCHAR(255), email VARCHAR(255) PRIMARY KEY, password VARCHAR(255), location VARCHAR(255), profile_url TEXT, fav TEXT, cart TEXT)")

# Admins Table
myCursor.execute("CREATE TABLE admins(name VARCHAR(255), email VARCHAR(255) PRIMARY KEY, password VARCHAR(255))")

# OTP Verification Table
myCursor.execute("CREATE TABLE verify(name VARCHAR(255), number VARCHAR(255), email VARCHAR(255), password VARCHAR(255), otp VARCHAR(255))")

# Customer Session Table
myCursor.execute("CREATE TABLE sessions(id VARCHAR(255), email VARCHAR(255), FOREIGN KEY (email) REFERENCES customers(email))")

# Admin Session Table
myCursor.execute("CREATE TABLE sessions_admin(id VARCHAR(255), email VARCHAR(255), FOREIGN KEY (email) REFERENCES admins(email))")

# Products Table
myCursor.execute("CREATE TABLE products(id VARCHAR(255) PRIMARY KEY, title VARCHAR(255), description TEXT, price INT, qty INT, review_count INT, stars INT, product_imgs TEXT)")

# Orders Table
myCursor.execute("CREATE TABLE orders(id VARCHAR(255), product_id VARCHAR(255), email VARCHAR(255), status INT, qty INT, shipping INT, discount INT, tax INT, date DATE)")




## ----- DEFAULT VALUES  -----

## ADMINS
myCursor.execute(f'''INSERT INTO admins VALUES ('Rahul S Rawat', 'rahul@mail.com', '{sha256("rahul123".encode()).hexdigest()}') ''')
myCursor.execute(f'''INSERT INTO admins VALUES ('Raju Bhole', 'raju@mail.com', '{sha256("raju123".encode()).hexdigest()}') ''')


## CUSTOMERS
myCursor.execute(f'''INSERT INTO customers VALUES ('Allan Gutierrez', '8745899652', 'gutierrez@mail.com', '{sha256("gutierrez123".encode()).hexdigest()}', 'mumbai', 'https://randomuser.me/api/portraits/men/19.jpg', '[]', '[]')''')
myCursor.execute(f'''INSERT INTO customers VALUES ('Erik Howell', '5487596524', 'howell@mail.com', '{sha256("howell123".encode()).hexdigest()}', 'mumbai', 'https://randomuser.me/api/portraits/men/50.jpg', '[]', '[]')''')
myCursor.execute(f'''INSERT INTO customers VALUES ('Louella Fields', '8745899652', 'fields@mail.com', '{sha256("fields123".encode()).hexdigest()}', 'mumbai', 'https://randomuser.me/api/portraits/women/73.jpg', '[]', '[]')''')
myCursor.execute(f'''INSERT INTO customers VALUES ('Brittany Reyes', '8745899652', 'reyes@mail.com', '{sha256("reyes123".encode()).hexdigest()}', 'mumbai', 'https://randomuser.me/api/portraits/women/33.jpg', '[]', '[]')''')
myCursor.execute(f'''INSERT INTO customers VALUES ('Jonathan Phillips', '8745899652', 'phillips@mail.com', '{sha256("phillips123".encode()).hexdigest()}', 'mumbai', 'https://randomuser.me/api/portraits/men/76.jpg', '[]', '[]')''')


## PRODUCTS ----


# > Electronics (Mobile)
myCursor.execute(f'''INSERT INTO products VALUES ('P1', 'SAMSUNG Galaxy Z Flip 4 Mobile Phone | Electronic', 'Unfold your world with next-level expression. Samsung Galaxy Z Flip4 offers compact portability that conveniently moves with your lifestyle. This is the phone that is uniquely you, with an innovative design, stylish colors, and custom accessories.', 40000, 6, 200, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/613jzPT0RbL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61jqaN-jq7L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71-K0XyfXOL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71tkKd28TfL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P2', 'Apple iPhone 12 Pro Mobile Phone | Electronic', 'Unfold your world with next-level expression. Samsung Galaxy Z Flip4 offers compact portability that conveniently moves with your lifestyle. This is the phone that is uniquely you, with an innovative design, stylish colors, and custom accessories.', 50000, 8, 300, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71r0E8xfKcL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/811cmNjnL4L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71zRSxCMpqL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61XlnSh6dQL._AC_SY741_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P3', 'OnePlus 10 Pro Mobile Phone | Electronic', 'Unfold your world with next-level expression. Samsung Galaxy Z Flip4 offers compact portability that conveniently moves with your lifestyle. This is the phone that is uniquely you, with an innovative design, stylish colors, and custom accessories.', 30000, 8, 100, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81qOD8EZTjL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61iEEZhRt5L._AC_SY741_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71-7y+YbRgL._AC_SY741_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61-p0VbGF1L._AC_SY741_.jpg"]') ''')


# > Electronics (Laptops)
myCursor.execute(f'''INSERT INTO products VALUES ('P4', 'Apple 2022 MacBook Air Laptop | Electronic', 'M2 chip: 13.6-inch Liquid Retina Display, 8GB RAM, 512GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera. Works with iPhone and iPad; Midnight', 60000, 6, 400, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/719C6bJv8jL._AC_SX522_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81jcKZq-EOL._AC_SX522_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61GAbMHjeYL._AC_SX522_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61HS4BY-4rL._AC_SX522_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P5', 'Alienware m15 R4 Gaming Laptop | Electronic', 'This item Alienware m15 R4 Gaming Laptop, 15.6 inch Full HD (FHD) - Intel Core i7-10870H, 16GB DDR4 RAM, 512GB SSD, NVIDIA GeForce RTX 3060 6GB GDDR6, Windows 10 Home - Lunar Light', 50000, 6, 225, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71Jp27bTQoL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/718r8bl1QbL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61x+yaABHGL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71eRgta2AaL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P6', 'HP 2022 New 15 Laptop | Electronic', 'This item HP 2022 New 15 Laptop, 15.6" HD LED Display, Intel Dual-Core Processor, Intel UHD Graphics, 16GB DDR4 RAM, 1TB SSD, Ethernet Port, USB Type-C, Long Battery Life, Windows 11', 45000, 6, 350, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71rmymgVWVL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71dl8gMSCrL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61UMl9B4kpL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/717yG6t-JlL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P7', 'MSI Stealth GS77 Gaming Laptop | Electronic', 'GreatPriceTech sells computers with custom/upgraded configurations to enhance system performance. If the computer has modifications as listed above, the manufacturer’s box was opened by our highly skilled technicians for testing, inspection, and installation of the upgrades according to the specifications advertised', 70000, 6, 450, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61eGXOnxveL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71HtlNvIg9L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51cm-broyiL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51n55v+VTkL._AC_SX466_.jpg"]') ''')


# > Electronics (Camera)
myCursor.execute(f'''INSERT INTO products VALUES ('P8', 'Canon EOS Rebel T7 DSLR Camera | Electronic', 'Perfect for beginners, this camera bundle offers the essential tools needed to take your SLR skills to new heights, all in one convenient package. No matter where your next adventure takes you, count on the EOS Rebel t7-s impressive 24.1 Megapixel CMOS sensor', 20000, 7, 450, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71EWRyqzw0L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71sQ1on0fuL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/717xSjyDRzL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/713ShDiciHL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P9', 'Sony Alpha a7 mirrorless Camera | Electronic', 'This item Sony Alpha a7 IIK E-mount interchangeable lens mirrorless camera with full frame sensor with 28-70mm Lens', 60000, 8, 500, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71G2PIzqK2L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71KGTpZLeaL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71WZI5qHRxL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71pMlSNXUdL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P10', 'Nikon D850 Digital SLR Camera | Electronic', 'The 28-300mm is a very sharp lens with a short focal distance which allows it to be used for Macro. It is an overall good lens and is the lens I take with me in situations where changing lens is not possible.', 54000, 6, 425, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71HJnJrxzEL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81pa13+aYUL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71lJPwprU-L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71S57zZExlL._AC_SX466_.jpg"]') ''')


# > Electronics (Headphones)
myCursor.execute(f'''INSERT INTO products VALUES ('P11', 'PRTUKYT 6S Wireless Bluetooth Headphone | Electronic', 'This item PRTUKYT 6S Wireless Bluetooth Headphones Over Ear, Hi-Fi Stereo Foldable Wireless Stereo Headsets Earbuds with Built-in Mic, Volume Control, FM for Phone/PC (Black & Gold)', 2100, 10, 35, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61U1o73WqUL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61JElKQH5CL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61LliuIf4JL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/611KilCeW1L._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P12', 'Wireless Earbud, Bluetooth 5.3 Headphones | Electronic', 'This item Wireless Earbud, Bluetooth 5.3 Headphones in Ear Stereo Bluetooth Earbuds Built in Mic, Wireless Earphones with LED Power Display and USB-C Charging, Mini Earbud with IP7 Waterproof and Touch Control', 2500, 8, 78, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/614mFoOdV3L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71hI5mp6vEL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/719VTfyDaoL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71CUZf1gfnL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P13', 'Srhythm NC25 Active Noise Cancelling Headphones | Electronic', 'This item Srhythm NC25 Active Noise Cancelling Headphones Bluetooth 5.3,ANC Stereo Headset Over-Ear with Hi-Fi,Mic,50H Playtime,Voice Assistant,Low Latency Game Mode', 5500, 12, 150, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61wbr2lSdJL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71nQikw87PL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/615DQ2hsdAL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61ctrTFEfmL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P14', 'MOVSSOU E7 Active Noise Cancelling Headphones | Electronic', 'This item MOVSSOU E7 Active Noise Cancelling Headphones Bluetooth Headphones Wireless Headphones Over Ear with Microphone Deep Bass, Comfortable Protein Earpads, 30 Hours Playtime for Travel/Work, Light Blue', 4800, 15, 142, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71qVNdfxQUL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/616lOYhZgjL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71hEhC7R1tL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71djOMxOenL._AC_SX466_.jpg"]') ''')


# > Electronics (Computer Accessories)
myCursor.execute(f'''INSERT INTO products VALUES ('P15', 'KNOWSQT Wireless Keyboard and Mouse Combo | Computer Accessories', 'This item KNOWSQT Wireless Keyboard and Mouse Combo, Milk Tea 104 Keys Full-Sized 2.4 GHz Round Keycap Colorful Keyboards, USB Receiver Plug and Play, for Windows, Mac, PC, Laptop, Desktop', 3700, 20, 24, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71OtavP510L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71ILBUV0T6L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61y2qBzFO-L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71M0fIkPejL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P16', 'Redragon S101 Wired Gaming Keyboard and Mouse Combo | Computer Accessories', 'PC GAMING KEYBOARD AND GAMING MOUSE COMBO: Includes Redragon RGB Backlit Computer Gaming Keyboard and RGB Backlit Gaming Mouse. ALL-IN-ONE PC GAMER VALUE KIT, Fantastic for Gamers (New Improved Version)', 3500, 28, 250, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71kr3WAj1FL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71uIslKmtoL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71H6y1GGbAL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71z+9JkYFJL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P17', 'Portable 60% Mechanical Gaming Keyboard | Computer Accessories', 'Mini portable 60% compact layout: MK-Box is a 68 keys mechanical keyboard have cute small size, separate arrow keys and all your F-keys you need, can use it for gaming or work while saving space', 2500, 45, 470, 3, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/618zZ7u3sUL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71VbXAHUnEL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71pkA0PtbiL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71cmj78pu+L._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P18', 'Logitech G502 HERO High Performance Wired Gaming Mouse | Computer Accessories', 'Hero 25K sensor through a software update from G HUB, this upgrade is free to all players: Our most advanced, with 1:1 tracking, 400-plus ips, and 100', 850, 30, 250, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61mpMH5TzkL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71sgEIlSvfL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61Z49vScNSL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61vThyaOrHL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P19', 'Redragon M908 Impact RGB LED MMO Mouse | Computer Accessories', 'Professional Gaming Mouse - Redragon M908 optical gaming mouse is designed with up to 12400 DPI, 5 adjustable DPI levels (500/1000/2000/3000/6200 DPI) meet your multiple needs, either for daily work or gaming', 700, 25, 320, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61kI0PIuXVL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61S7+9dKMBL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71FH3rLcYNL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/613YRdgeRvL._AC_SX466_.jpg"]') ''')


# > Fashion (Men's Fashion)
myCursor.execute(f'''INSERT INTO products VALUES ('P20', 'Sandbank Slim Fit Lightweight | Men Fashion', 'Polyester, Zipper closure, Hand Wash Only Material:100% Polyester, lightweight and high-quality fabric makes this jacket comfortable and soft, Classic design,slim fit wear', 1200, 350, 40, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61dJgRgP8YL._AC_UX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/614qn4yPDHL._AC_UX522_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71LEM7Lo5iL._AC_UX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61cY2MRGEsL._AC_UX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P21', 'COOFANDY Mens Knitted Hoodies Casual | Men Fashion', 'This knitted sweater hoodie made of elastic soft fabric and thick material, warmth, durability, provides a soft and warm wearing experience in autumn, winter and spring', 1400, 200, 500, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/91Uk5CAaauL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/91rB4pogf3L._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/91ssYRPk9RL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/A16JPSRdRgL._AC_UY550_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P22', 'Screenshotbrand Mens Urban Hip Hop | Men Fashion', 'SCREENSHOT BRAND is a New Line of Streetwear Fashion Company Launched Exclusively for E-Commerce. Our Inspiration is Based on Inner City Statements, and Cultural Movements. Even Though we are Under a Constant State of Evolution', 950, 47, 400, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/819DlrA4hHL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81QmX7sirWL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61anFHEQpfL._AC_UX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81yvc76VthL._AC_UY550_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P23', 'Mens Fashion Hoodies Athletic Sweatshirt | Men Fashion', '90% Polyester, 10% Cotton, Imported
Snap closure, Machine Wash, ➤Fabric：90% Cotton, ➤Machine washing and hand washing, ➤Design: Pullover hoodie, soft fabric, strong and durable,Anti-shrinkage', 780, 20, 700, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61xfktpAFtL._AC_SX466._SX._UX._SY._UY_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61zP3YG7E4L._AC_SX466._SX._UX._SY._UY_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61wBztb1brL._AC_SX466._SX._UX._SY._UY_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61rfCbwAQaL._AC_SX466._SX._UX._SY._UY_.jpg"]') ''')


# > Fashion (Women's Fashion)
myCursor.execute(f'''INSERT INTO products VALUES ('P24', 'AUTOMET Womens Casual Plaid Shacket | Women Fashion', 'Made of high quality 55% Nylon/ 45% Spandex fabric, skin-friendly, soft and comfortable to wear, will keep your warm and fashion style in fall, spring and cold winter, Machine Wash', 340, 55, 450, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/614VXl7BjqL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61qKwt-MwgL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/717+KL59oyL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UIiPiT2jL._AC_UX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P25', 'Trendy Queen Womens Mock Turtleneck | Women Fashion', 'Material: Made of 80% Polyester,15% Viscose,5% Spandex.Super soft,comfortable and elastic, high-stretch fabric with a second-skin feel,fall baisc for women', 450, 60, 300, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51GLcp-f9DL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51yBCA-6smL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51rYy+zewHL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61VQWuhOrVL._AC_UX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P26', 'SheIn Womens Double Breasted Long Vest | Women Fashion', 'Sleeveless, double breasted , open front, lapel collar, long blazer jacket, fall outfits; Sweet and sexy style shows your unique personal charm and produces an elegant visual effect', 1500, 45, 250, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71AGfC1OzfL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/711bKnxc7oL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71qZjqYHWpL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71iQyMjB8wL._AC_UY550_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P27', 'Vfshow Womens Elegant Patchwork Pockets | Women Fashion', 'Garments in different colors/patterns may use different materials, please check the listing pictures. Style: Round Neckline, Sleeveless, Random Floral Print, Patchwork Design, Two handy pockets', 1200, 50, 70, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61RyvsuJYQL._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71v9njpbd-S._AC_UY550_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/718Lc-svagL._AC_UX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61pKuEuftcS._AC_UY550_.jpg"]') ''')


# > Fashion (Child's Fashion)
myCursor.execute(f'''INSERT INTO products VALUES ('P28', 'MODAFANS Girls Buffalo Plaid Fleece Hoodies | Kid Fashion', '%Polyester, Double sided fleece,soft skin-friendly fabric make your kids warm. Features: Fashion Buffalo Plaid sweatshirt, pullover hoodies, warm and soft material, lightweight, fuzzy fleece hoodies, comfortable', 550, 40, 350, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71pkfrzeouL._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71CqMhVki0L._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71JcsNCzLwL._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71ozifMcsKL._AC_UX569_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P29', 'Baby First Birthday Outfit | Kid Fashion', 'The outfit material,Soft and breathable for babys skin .Machine wash. Adorable 1st birthday outfit,Fashionable wave point bowtie design has modern style,The unique design makes him even more eye-catching on his one year old birthday party', 1200, 50, 120, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71EO5K2UO2L._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61O2tHKQ57L._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71e5yhJKQEL._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61nXuAQUeML._AC_UX569_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P30', 'Ikecedfg Childrens Sweatshirt Set Hoodie | Kid Fashion', 'Material - 100% High Grade Polyester. Light And Soft Material,Very Comfortable To Wear.Provides The Comfortable Enjoyment For Your Kids.Tailor-Made For Children', 1300, 48, 240, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71mWxs0BPSL._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71INghXh7kL._AC_UX569_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71BgW19U1hL._AC_SX569._SX._UX._SY._UY_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71IGvB+SenL._AC_SX679._SX._UX._SY._UY_.jpg"]') ''')


# > Smart Home (Home Assistant)
myCursor.execute(f'''INSERT INTO products VALUES ('P31', 'Echo Dot Smart Home Assistant | Smart Home', 'Use your voice to play a song, artist, or genre through Amazon Music, Apple Music, Spotify, Pandora, and others. With compatible Echo devices in different rooms, you can fill your whole home with music.', 2000, 45, 250, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/6182S7MYC2L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61QYCC1rbsL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61MZfowYoaL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61LipgQ484L._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P32', 'Echo With premium sound, Home Assistant | Smart Home', 'Call friends and family who have the Alexa app or an Echo device. Instantly drop in on other rooms or announce to the whole house that dinner ready. Rich, detailed sound that automatically adapts to any room', 2500, 45, 300, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61y4J2vTwFL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/715DvDSVV-L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61JlDVS+oXL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61V5O0UpgqS._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P33', 'Google Home Mini Home Assistant | Smart Home', 'Adapt retro alarm clock appearance to making this stand more attractive and compatible with the design of Google Home Mini. Perfect fit into any living room as decoration and improve its aesthetic level', 1400, 50, 250, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71vI939eizL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71HrZv5nsoL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61wguCbH8ML._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71d442ejSHL._AC_SX679_.jpg"]') ''')


# > Smart Home (Doorbell)
myCursor.execute(f'''INSERT INTO products VALUES ('P34', 'Ring Video Doorbell 4 video | Smart Home', 'Start recording before you even receive a motion alert with color Pre-Roll – the first feature of its kind for battery-powered doorbells. With up to 4 extra seconds of video, you’ll know what happened', 6000, 70, 24, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71hq4HgdiZL._SY450_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/519mUYxI5IL._SY450_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61AoDNTEm4L._SY450_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51i2eBDu3LL._SY450_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P35', 'Wireless Doorbell by ak-ship | Smart Home', 'This item Wireless Doorbell by ak-ship, 1,000ft Range Loud Enough with 4 Volume Levels and Mute Mode Door Chimes LED Flashing', 800, 20, 28, 3, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/511H4DRt1AL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UmA0hqkVL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71Sois9HW9L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61xc750fXTL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P36', 'Wireless Doorbell Door bell Waterproof | Smart Home', 'SIMPLE INSTALLATION: Just need to plug the doorbell receiver into a socket and fix the button on a wall with the accessories provided; includes 2 screws, 1 double-sided bonding tape', 750, 25, 40, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51-uqlqbtwL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61kmJZeQ1wL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81SeUngJ6+L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61A3w-+hypL._AC_SX466_.jpg"]') ''')


# > Smart Home (Lights)
myCursor.execute(f'''INSERT INTO products VALUES ('P37', 'BlissLights Sky Lite 2.0 - RGB LED Laser | Smart Home', 'Incorporates a direct diode Laser, precision glass optics, and holographic technologies to create an otherworldly visual experience that cannot be matched', 750, 50, 30, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51uQC1if4sL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71oBwOAgg3L._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81pFbrsxFWL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41DvMCmC9+S._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P38', 'AIKVSXER Flush Mount Ceiling Light | Smart Home', 'This item AIKVSXER Flush Mount Ceiling Light 12 Inch - Smart Ceiling Light 24W 2400LM - Smart Home Lighting LED Ceiling Light - Dimmable Color Changing Ceiling Light - RGB Ceiling Light with Alexa Google Home', 480, 40, 24, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61a+bCwgNeL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71QF3U3da8L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/811v2-sZtGL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71E6-L3R1KL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P39', 'TJOY Alexa Smart Light Bulbs | Smart Home', 'This item TJOY Alexa Smart Light Bulbs, WiFi Led Light Bulb Work with Alexa&Google Home, Dimmable RGB Color Changing 2700-6500K Smart App Control (2.4Ghz Only), A19 E26 9W (60W Equivalent) 800 Lumen ,1 Pack', 800, 40, 240, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61Mmh1K6CVL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61Tzi0T2naL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81OZy+uf6XL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71KCexn3VGL._AC_SX679_.jpg"]') ''')


# > Home and Kitchen (Fridge)
myCursor.execute(f'''INSERT INTO products VALUES ('P40', 'Smart Counter Depth 4-Door Refrigerator | Home and Kitchen', 'This smart counter depth refrigerator features the AutoFill Water Pitcher, a built-in pitcher that automatically refills with fresh, filtered water and a Dual Ice Maker with nugget-style Ice Bites', 45000, 25, 35, 4, '["https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/pdp/10142021/Refrigerator_RF23A9071SR-AA_71-7-8x35-7-8x28-1-2.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/pdp/rf23a9071sr-aa/gallery/RF23A9071SR_01_Stainless_Steel_SCOM.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/pdp/rf23a9071sr-aa/gallery/RF23A9071SR_04_Stainless_Steel_SCOM.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/pdp/rf23a9071sr-aa/gallery/RF23A9071SR_08_Stainless_Steel_SCOM.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P41', '4-Door refrigerator with Family Hub | Home and Kitchen', 'This smart counter depth refrigerator features the AutoFill Water Pitcher, a built-in pitcher that automatically refills with fresh, filtered water and a Dual Ice Maker with nugget-style Ice Bites', 50000, 5, 2, 4, '["https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/06292022/rf23a9771sg/RF23A9771SG_01_Black_SCOM.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/06292022/rf23a9771sg/RF23A9771SG_04_Black_SCOM.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/pdp/rf23a9771sg-aa/gallery/RF23A9771SG_05_Black-Stainless-Steel_SCOM.jpg", "https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/06292022/rf23a9771sg/RF23A9771SG_07_Black_SCOM.jpg"]') ''')


# > Home and Kitchen (Microwave)
myCursor.execute(f'''INSERT INTO products VALUES ('P42', 'TOSHIBA EM131A5C-SS Countertop Microwave Oven | Home and Kitchen', 'This item TOSHIBA EM131A5C-SS Countertop Microwave Oven, 1.2 Cu Ft with 12.4" Turntable, Smart Humidity Sensor with 12 Auto Menus, Mute Function & ECO Mode, Easy Clean Interior, Stainless Steel & 1100W', 10000, 30, 20, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61GFwwSWD6L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/711GsOdRgBL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71S3+Xa2APL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71RdKDbSy7L._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P43', 'COMFEE EM720CPL-PMB Countertop Microwave Oven | Home and Kitchen', 'This item COMFEE EM720CPL-PMB Countertop Microwave Oven with Sound On/Off, ECO Mode and Easy One-Touch Buttons, 0.7cu.ft, 700W, Black', 7000, 20, 15, 3, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81dsDxFMqxL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71wDlyjVn-L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81XJoHzf63L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71e3wX1C+-L._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P44', 'Commercial Chef Countertop Microwave Oven | Home and Kitchen', 'With the Commercial Chef CHM660B microwave oven you get 600 watts of cooking power and a . 6 cubic foot interior. Easy to use mechanical dials allow you to set the timer that ranges from 1 to 30 minutes and to Select from among the six cooking power levels', 6500, 10, 5, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81RJDfK+qrL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71g5hKTnFVL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71VUUiGLF-L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81z3mvz4ZxL._AC_SX679_.jpg"]') ''')


# > Home and Kitchen (Home Decore)
myCursor.execute(f'''INSERT INTO products VALUES ('P45', 'Sugutee Elephant Decor, Large Elephant Home Decore | Home and Kitchen', 'Elephant decoration is very suitable for home decoration, whether as a holiday decoration or as an ordinary tabletop decoration.It looks very beautiful in any space', 250, 50, 120, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71g2YqE2koL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71+-K320nSL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61oC+NO536L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71LB6lzGsNL._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P46', 'YJ Fake Flowers with Vase | Home and Kitchen', 'Flower arrangement with vase include white roses, artificial eucalyptus flowers fake plants and matching one grass vase. The glass vase with heart-shaped and spherical pendants and hemp rope', 380, 40, 150, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71T5o5Lq8yL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/619ejPyS6ES._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61dwAxscYVL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71qDcJbnp8S._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P47', 'GenSwin Battery Operated Flameless Led Candles Home Decore | Home and Kitchen', 'Flower arrangement with vase include white roses, artificial eucalyptus flowers fake plants and matching one grass vase. The glass vase with heart-shaped and spherical pendants and hemp rope', 380, 40, 150, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71T5o5Lq8yL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/619ejPyS6ES._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61dwAxscYVL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71qDcJbnp8S._AC_SX679_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('P48', 'Tiered Tray Decor 10 Pieces Farmhouse Home Decore | Home and Kitchen', 'This farmhouse tiered tray decor decor with a lot of warm home atmosphere, which is an adorable addition for decorating your farmhouse kitchen', 400, 20, 120, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51wIZVUxbAL._AC_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/715A6qOQ45L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71-SNtoyHAL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81uo56ur-aL._AC_SX679_.jpg"]') ''')


# > Home and Kitchen (Washing Machine)
myCursor.execute(f'''INSERT INTO products VALUES ('p49', 'BLACK DECKER Small Portable Washer, Washing Machine | Home and Kitchen', 'When it comes to washing machines, this outstanding BLACK+DECKER portable washer (17-11/16” x 18-1/16” x 31-1/2”) is your ultimate solution to immaculately clean clothing for household use. There are 5 cycles to choose from with this fantastic 0.9 cu', 25000, 10, 5, 4, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61tNdgVDSLL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/813pPgIdxPL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81l1GzwQtlL._AC_SX466_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71IpSUkWjIL._AC_SX466_.jpg"]') ''')

myCursor.execute(f'''INSERT INTO products VALUES ('p50', 'Portable Washing Machine with Draining Pump | Home and Kitchen', 'Now includes a built-in water drain pump. The Strong And Durable Portable Washing Machines Features Two Tubs 1 For Washing And 1 For Spinning', 30000, 8, 60, 5, '["https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61wbbj0yOKL._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71uCK5+Oa6L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71mwrkPST5L._AC_SX679_.jpg", "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71gvuvDQbYL._AC_SX679_.jpg"]') ''')


mycon.commit()